# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Tailscale
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    - run: tailscale status
    - name: create env file
      run: |
        touch .env
        echo ADT_URL ="$(tailscale ip -4 cubi5):50001" >> .env
        echo ADT_USER =${{ secrets.ADT_USER }} >> .env
        echo ADT_PASS =${{ secrets.ADT_PASS }} >> .env
        echo ABAP_PACKAGE =${{ secrets.ABAP_PACKAGE }} >> .env
    - run: cat .env
    - run: npm install
    - run: npm run build
    - run: npm test
